---
title: "Untitled"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: scroll
---

```{r setup, include=FALSE}
library(flexdashboard)
library(DT)
library(stringr)
source("Bilixixi.R")
```


Page 1
===================================== 
<!-- Column {data-width=650} -->
<!-- ----------------------------------------------------------------------- -->

### Chart A


```{r vie}
# vie[,c("titlelink","lengthnum","viewnum","text","upload","uplink")]

#htmltools::tags$script(src = "myselect.js")
#htmltools::tags$script(src = "myselect copy.js")
options(width = 10000)

x=datatable(vie, filter = 'top',plugins =list('select'),style ="bootstrap",#class="hover",
          #extensions = 'FixedColumns',
#####################

          options = list(
          initComplete = JS(
            "function(settings, json) {
            $(window).resize(function() {
            oTable.fnAdjustColumnSizing();
            })}"
          ),
                        sPaginationType = list('listbox'),
                        #pagingType="numbers",
                        pageLength = 30,
                        language = list(search = '搜索:',
                        lengthMenu='每页显示 _MENU_ 个视频',
                        zeroRecords='什么也没找到，换个关键词试试',
                        info='现在第 _PAGE_ 页 共 _PAGES_ 页',
                        infoEmpty='没有可显示的页面',
                        infoFiltered='(从 _MAX_ 项中搜索)',
                        paginate=list(previous='上一页',
                        'next'='下一页',
                        first='第一页',
                        last='最后一页')),
                        
                        columnDefs = list(
                        list(targets=2,
                        render = JS(
                     "function(data, type, row, meta) {",
                     "return type === 'display'?",
                     "'<span title=\"'+data +'\">'+Math.floor(data/60) + '分'+Math.floor(data%60)+'秒</span>' : data;",
                     "}")
              ),
              list(targets=3,
                   render = JS(
                     "function(data, type, row, meta) {",
                     "return type === 'display' && data>=10000 ?",
                     "'<span title=\"' + data + '\">'+Math.floor(data/1000)/10+'万</span>' : data;",
                     "}")
              ),
              list(targets=5,
                   render = JS(
                     "function(data, type, row, meta) {",
                     "return type === 'display' ?",
                     "'<span title=\"' + data + '\">' + data.substr(5, 12) + '</span>' : data;",
                     "}")
              ),
              list(targets= '_all',
                createdCell=JS(
                  "function (td, cellData, rowData, row, col) {",
                    "$(td).css('padding', '8px 4px 8px 4px')",
                  "}")
              ),
              list(targets=2:5,
                   class="dt-body-center"),
              list(targets='_all',
                   class="dt-head-center"),
              list(targets='_all',
                   className = 'dt-middle')
          )),
          escape = FALSE,
          colnames = c("标题","时长","观看","弹幕","日期","阿婆主")
          )

css_text <- "
.dt-middle {vertical-align: middle;}
"
css <- htmltools::tags$style(type = "text/css", css_text)
htmlwidgets::prependContent(x, htmltools::tags$head(css))

```

最近更新: `r lastdate` hmmm

<!-- Column {data-width=350} -->
<!-- ----------------------------------------------------------------------- -->


帮助
===================================== 

hehehe