---
title: "哔哩嘿嘿动画!"
#author: "☁️B站罗云熙首页拯救计划☁️"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: scroll
    theme: bootstrap
    logo: BilixixiLogo.png
    navbar:
       - { title: "首页", href: "index.html", align: left }
       - { title: "帮助", href: "help.html", align: left }
---

```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = FALSE,message=FALSE,warning=FALSE, cache=FALSE)
library(wordcloud2)
library(DT)
library(stringr)
library(crosstalk)
source("Bilixixi.R")
try = SharedData$new(vie)

```



s {.sidebar data-width=260 }
-----------------------------------------------------------------------


<center>

<h1> TEST</h4>

哔哩熙熙，我们是认真的

</center>

### s {.mobile data-height=120}

```{r}
bscols(
filter_checkbox("myfilter1", "☁️最新上传☁️", try, ~ifelse(difftime(lastdate,upload,units = "days") <= 3, "近3天",ifelse(difftime(lastdate,upload,units = "days") <= 7, "近3-7天", "7天以上"))),
filter_checkbox("myfilter2", "☁️视频时长☁️", try, ~ifelse(lengthnum < 300 , "5分以内",ifelse(lengthnum < 900, "5-15分", "15分以上"))),
filter_checkbox("myfilter3", "☁️播放数据☁️", try, ~ifelse(viewnum < 1000 , "1千以下",ifelse(lengthnum < 10000, "1千-1万", "1万以上"))),
filter_checkbox("myfilter4", "☁️标题类型☁️", try, ~ifelse(tag==T, "多人向" , "个人向")))
```


###  {.no-mobile}


```{r}

filter_checkbox("myfilter1", "☁️最新上传☁️", try, ~ifelse(difftime(lastdate,upload,units = "days") <= 3, "近3天",ifelse(difftime(lastdate,upload,units = "days") <= 7, "近3-7天", "7天以上")),inline = T)

filter_checkbox("myfilter2", "☁️视频时长☁️", try, ~ifelse(lengthnum < 300 , "5分以内",ifelse(lengthnum < 900, "5-15分", "15分以上")),inline = T)

filter_checkbox("myfilter3", "☁️播放数据☁️", try, ~ifelse(viewnum < 1000 , "1千以下",ifelse(lengthnum < 10000, "1千-1万", "1万以上")),inline = T)

filter_checkbox("myfilter4", "☁️标题类型☁️", try, ~ifelse(tag==T, "多人向" , "个人向"),inline = T)

filter_select("myfilter5", "标题查询", try, ~title)
filter_select("myfilter6", "UP主查询", try, ~uplink)

# filter_slider("myfilter7", "播放量", try, ~viewnum, width = "100%")
# filter_slider("myfilter8", "弹幕数", try, ~text, width = "100%")

```


<center>
最近更新: `r lastdate` | 微博: test
</center>


Column {data-width=500}
-----------------------------------------------------------------------

###

```{r vie}

#htmltools::tags$script(src = "mysetting.js")

datatable(try, rownames = FALSE, filter = 'top',style ="bootstrap",selection="none",
          options = list(
            deferRender=TRUE,
            lengthChange=F,
            search = list(regex = TRUE, search = ''),
                        pagingType="numbers",
                        pageLength = 30,
                        language = list(search = '正则搜索:',
                        lengthMenu='每页显示 _MENU_ 个视频',
                        zeroRecords='什么也没找到，换个关键词试试',
                        info='现在第 _PAGE_ 页 共 _PAGES_ 页',
                        infoEmpty='没有可显示的页面',
                        infoFiltered='(从 _MAX_ 项中搜索)',
                        paginate=list(previous='上一页',
                        'next'='下一页',
                        first='第一页',
                        last='最后一页')),

                        columnDefs = list(
                        
                        list(targets=1,
                        render = JS(
                     "function(data, type, row, meta) {",
                     "return type === 'display'?",
                     "'<span title=\"'+data +'\">'+Math.floor(data/60) + '分'+Math.floor(data%60)+'秒</span>' : data;",
                     "}")
              ),
              list(targets=6,
                   visible=FALSE
              ),
              list(targets=7,
                   visible=FALSE
              ),
              list(targets=2,
                   render = JS(
                     "function(data, type, row, meta) {",
                     "return type === 'display' && data>=10000 ?",
                     "'<span title=\"' + data + '\">'+Math.floor(data/1000)/10+'万</span>' : data;",
                     "}")
              ),
              list(targets=4,
                   render = JS(
                     "function(data, type, row, meta) {",
                     "return type === 'display' ?",
                     "'<span title=\"' + data + '\">' + data.substr(5, 12) + '</span>' : data;",
                     "}")
              ),
              list(targets= '_all',
                createdCell=JS(
                  "function (td, cellData, rowData, row, col) {",
                    "$(td).css('padding', '8px 4px 8px 4px')",
                  "}")
              ),
              list(targets=1:4,
                   class="dt-body-center"),
              list(targets='_all',
                   class="dt-head-center")
          )),
          escape = FALSE,
          colnames = c("标题","时长","观看","弹幕","日期","UP","隐藏","隐藏2")
          )



```



Column {data-width=10}
-----------------------------------------------------------------------

```{r}

#filter_slider("otl", "时间范围", try, ~upload,timeFormat = "%F",width = "100%")
#filter_slider("lengthnum", "时长", try, column=~log(lengthnum), step=1, width=200)
#filter("lengthnum", "时长", try, column=~log(lengthnum), step=1, width=200)

```

